### PR TITLE
Updated tags.ejs && categories.ejs

### PR DESCRIPTION
**Pull request by ramazanaltintop**
Updated tags.ejs && categories.ejs.

tags_categories

### CODE REVIEW

**Comment by wujun234** [comment]
change from a list to one line? what's the purpose?

**Comment by ramazanaltintop** [comment]
It wasn't visible how many tags and categories there were on my website. Additionally, tags and categories were not listed.

**Comment by wujun234** [comment]
> It wasn't visible how many tags and categories there were on my website. Additionally, tags and categories were not listed.

can u share ur display before the change? mine looks as expected

image
image

**Comment by ramazanaltintop** [comment]
Unfortunately it looks empty.
tags & categories preview

**Comment by wujun234** [comment]
> Unfortunately it looks empty. tags & categories preview

anyways, since u can get the value by using `site.tags` instead of `site.tags.data`, so the point is still changed from the list to one line, correct?

**Comment by ramazanaltintop** [comment]
> > Unfortunately it looks empty. tags & categories preview
> 
> anyways, since u can get the value by using `site.tags` instead of `site.tags.data`, so the point is still changed from the list to one line, correct?

Yes, that's correct.

**Comment by wujun234** [comment]
also added support for Turkish, correct me if i'm wrong

**Comment by wujun234** [comment]
I still prefer the list, so added a config to support your demands, try this
```
style:
  tags:
    # support line, list; default list
    display: line
  categories:
    # support line, list; default list
    display: line
```

image

**Comment by ramazanaltintop** [comment]
> I still prefer the list, so added a config to support your demands, try this
> 
> ```
> style:
>   tags:
>     # support line, list; default list
>     display: line
>   categories:
>     # support line, list; default list
>     display: line
> ```
> 
> image

Thank you, it's very nice.

**Pull request merged**
